apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: user-db
  name: user-db
  namespace: dev
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      io.kompose.service: user-db
      name: user-db
      product: sockshop
      stage: dev
      tier: data
      version: "2.1"
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        dynatrace/instrument: "false"
        pipeline.build: 2.1.0.3723
        pipeline.project: sockshop
        pipeline.stage: dev
        sidecar.istio.io/inject: "false"
        support.channel: '#support-sockshop-data'
        support.contact: mary.poppins@sockshop.com
      creationTimestamp: null
      labels:
        io.kompose.service: user-db
        name: user-db
        product: sockshop
        stage: dev
        tier: data
        version: "2.1"
    spec:
      containers:
      - env:
        - name: MONGODB_ADMIN_PASSWORD
          value: password
        - name: MONGODB_USER
          value: user
        - name: MONGODB_PASSWORD
          value: password
        - name: MONGODB_DATABASE
          value: default
        image: mongo
        imagePullPolicy: Always
        name: user-db
        ports:
        - containerPort: 27017
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/db
          name: user-db-mongodata
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: user-db-mongodata
        persistentVolumeClaim:
          claimName: user-db-mongodata
status: {}
